### ISSUE TITLE
You should add.

### ISSUE THREAD

**Issue by MelisseLima** [orhun/orhun#1]
**Blackbird**

Blackbird singing in the dead of night
Take these broken wings and learn to fly
All your life
You were only waiting for this moment to arise
Blackbird singing in the dead of night
Take these sunken eyes and learn to see
All your life
You were only waiting for this moment to be free
Blackbird fly, blackbird fly
Into the light of a dark black night
Blackbird fly, blackbird fly
Into the light of a dark black night
Blackbird singing in the dead of night
Take these broken wings and learn to fly
All your life
You were only waiting for this moment to arise
You were only waiting for this moment to arise
You were only waiting for this moment to arise

**Comment by WKFO** [comment]
wtf

**Comment by crxssed7** [comment]
huh

**Comment by iop3** [comment]
wth

**Comment by choose-a-new-username** [comment]
the fuck
